# 使用 Serverless Framework 來自動將 FastAPI 部署到 AWS Lambda 並通過 API Gateway 提供 HTTPS 支援。
service: fastapi-lambda-crud

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, 'dev'}  # 默認使用 'dev'，可通過命令行參數指定 stage
  versionFunctions: true

functions:
  app:
    handler: app/lambda_handler.lambda_handler   # 定義 Lambda 函數的入口點，這裡的 `handler` 指向 `app/lambda_handler.py` 中的 `lambda_handler` 函數，作為 Lambda 的執行入口。
    events:
      - http:
          path: hello
          method: get
          cors: true

    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
      preTrafficHook: preHook
      postTrafficHook: postHook
      alarms:
        - FooAlarm           # Logical ID (CloudFormation 模板中定義的唯一標是符)
        - name: BarAlarm     # 對象 (已存在的 AWS 資源名稱)

  preHook:
    handler: app.hooks.pre_handler                # 流量切換之前

  postHook:
    handler: app.hooks.post_handler               # 流量切換之後

plugins:
  - serverless-python-requirements            # 引入插件，用於自動打包和處理 Python 依賴項。
  - serverless-wsgi                           # 引入 `serverless-wsgi` 插件，適配 FastAPI 與 Lambda。
  - serverless-plugin-canary-deployments

custom:
  pythonRequirements:
    dockerizePip: true                        # 使用 Docker 打包依賴，確保與 Lambda 環境一致。
  wsgi:
    app: app.main.app                         # 指向 FastAPI app

resources:
  Resources:
    FooAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: LambdaFunctionErrors-FooAlarm-${self:provider.stage}
        MetricName: Errors
        Namespace: AWS/Lambda
        Statistic: Sum
        Period: 300
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold

    BarAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: LambdaFunctionErrors-BarAlarm-${self:provider.stage}
        MetricName: Errors
        Namespace: AWS/Lambda
        Statistic: Sum
        Period: 300
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
