# name: Deploy to AWS Lambda

# on:
#   push:
#     branches:
#       - dev
#       - main
#   pull_request:
#     branches:
#       - dev
#       - main

# jobs:
#   test_and_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3  # Use the latest version of the checkout action to pull the code

#       - name: Set up Python
#         uses: actions/setup-python@v4  # Use the latest version of the Python setup action
#         with:
#           python-version: '3.11'

#       - name: Ensure requirements.txt is UTF-8 without BOM
#         run: |
#           if file requirements.txt | grep -q "with BOM"; then
#             echo "Converting requirements.txt to UTF-8 without BOM"
#             mv requirements.txt requirements.txt.bak
#             iconv -f utf-8 -t utf-8 -c requirements.txt.bak > requirements.txt
#           else
#             echo "requirements.txt is already in correct format"
#           fi
#         # This step ensures that the requirements.txt file is in UTF-8 format without BOM (Byte Order Mark)

#       - name: Convert line endings to Unix format
#         run: |
#           sudo apt-get install -y dos2unix
#           dos2unix requirements.txt
#         # Converts line endings in the requirements.txt file to the Unix format (LF) to avoid compatibility issues

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#         # Installs Python dependencies based on the requirements.txt file

#       - name: Run tests
#         run: |
#           export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE  # Set PYTHONPATH to point to the project root directory
#           pytest
#         # Runs tests using the pytest framework after setting the PYTHONPATH

#       - name: Install Serverless CLI
#         run: |
#           npm install -g serverless
#         # Installs the Serverless Framework CLI globally

#       - name: Install Serverless plugins
#         run: |
#           npm install --save serverless-python-requirements
#           npm install --save serverless-wsgi
#           npm i --save-dev serverless-plugin-canary-deployments
#         # Installs necessary Serverless plugins, including:
#         # - serverless-python-requirements for handling Python dependencies
#         # - serverless-wsgi to adapt FastAPI to AWS Lambda
#         # - serverless-plugin-canary-deployments for gradual traffic shifting

#       - name: Deploy to AWS Lambda
#         run: |
#           serverless deploy --stage ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
#           # If the push is to the main branch, set the stage to 'prod'
#           # If the push is to another branch (e.g., dev), set the stage to 'dev'
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Fetch AWS credentials from GitHub Secrets
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: us-east-1  # Ensure the correct AWS region is set (modify if necessary)
#           SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}  # Use Serverless Access Key to authenticate
