name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 使用最新版本

      - name: Set up Python
        uses: actions/setup-python@v4  # 使用最新版本
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE  # 設置 PYTHONPATH 指向項目根目錄
          pytest

      - name: Install Serverless CLI
        run: |
          npm install -g serverless

      - name: Install Serverless plugins
        run: |
          npm install --save serverless-python-requirements
          npm install --save serverless-wsgi

      - name: Deploy to AWS Lambda
        run: |
          serverless deploy --stage dev  # 執行 Serverless 部署
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # 從 GitHub Secrets 中讀取 AWS 資訊
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # 確保你設置了區域（如果需要）
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}  # 使用 Serverless Access Key
