# name: Deploy to AWS Lambda

# on:
#   push:
#     branches:
#       - dev
#       - main
#   pull_request:
#     branches:
#       - dev
#       - main

# jobs:
#   test_and_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3  # 使用最新版本

#       - name: Set up Python
#         uses: actions/setup-python@v4  # 使用最新版本
#         with:
#           python-version: '3.11'

#       - name: Ensure requirements.txt is UTF-8 without BOM
#         run: |
#           if file requirements.txt | grep -q "with BOM"; then
#             echo "Converting requirements.txt to UTF-8 without BOM"
#             mv requirements.txt requirements.txt.bak
#             iconv -f utf-8 -t utf-8 -c requirements.txt.bak > requirements.txt
#           else
#             echo "requirements.txt is already in correct format"
#           fi

#       - name: Convert line endings to Unix format
#         run: |
#           sudo apt-get install -y dos2unix
#           dos2unix requirements.txt

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run tests
#         run: |
#           export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE  # 設置 PYTHONPATH 指向項目根目錄
#           pytest

#       - name: Install Serverless CLI
#         run: |
#           npm install -g serverless

#       - name: Install Serverless plugins
#         run: |
#           npm install --save serverless-python-requirements
#           npm install --save serverless-wsgi
#           npm i --save-dev serverless-plugin-canary-deployments

#       - name: Deploy to AWS Lambda
#         run: |
#           serverless deploy --stage ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
#           # 如果推送到 main 分支，則 stage 設置為 prod
#           # 如果推送到其他分支（如 dev），則 stage 設置為 dev
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # 從 GitHub Secrets 中讀取 AWS 資訊
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: us-east-1  # 確保你設置了區域（如果需要）
#           SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}  # 使用 Serverless Access Key
